### ISSUE TITLE
Minimal example with current version of build tools?

### ISSUE THREAD

**Issue by Coding-Crashkurse** [glin/shiny-react-example#4]
Hello glin,

thank you for this great repo. I try to build something similar with Vue.js, but the new CLI Tools seems to work quite differently. Is there a chance you create a similar minimal example with a current version of vue or react?
I was not able to make R Shiny run in combination with the webpack dev server.
https://stackoverflow.com/questions/63089190/vue-config-js-creating-a-single-main-js-file-and-serve-it-from-static

Can you help me? 
Thank you :-)

**Comment by glin** [comment]
Well, the dev server setup does seem to be broken right now, but it's a different reason for me. In Chrome, the proxying to Shiny just doesn't work at all:
```
sockjs.js:2999 WebSocket connection to 'ws://localhost:4000/sockjs-node/288/d10izo1w/websocket' failed: WebSocket is closed before the connection is established.
```

In Firefox, it does work, but it takes like 15 seconds to connect with Shiny.

I don't know what's going on, but I would recommend just not using the dev server for now. I never found the hot reloading to be very useful anyway.

For Vue + Shiny, this is not a minimal example, but there's https://github.com/glin/neostocks using a current version of Vue.

**Comment by Coding-Crashkurse** [comment]
Thank you very much for your answer. That is unfortunate to hear. So you recommend to just serve the dist/index.html file and always recompile the file when adding data from Shiny to test it? This is a bit of a hassle to debug or update the app, but it overall it worked. 
I already checked out you neostocks app, but I was not able to run it at it because of multiple errors from npm. 

In general it seems quite promising to use something like Vuetify to build the UI and let shiny do where shiny shines :-)

**Comment by glin** [comment]
Yes, I'd recommend always rebuilding the JS bundle. It's not too bad if you use webpack's `--watch` mode to automatically rebuild on file changes. Once the JS is rebuilt, you can refresh the page to get the new UI.

**Comment by Coding-Crashkurse** [comment]
Great, I will try that. Thank you for your time and effort :-)

**Comment by glin** [comment]
I took another look at this and figured out the problem. Shiny 1.5.0 added another websocket connection that has to be proxied, so I've fixed this in https://github.com/glin/shiny-react-example/commit/d078bdc74b54c664d950a0b4220ae76bbb37bbe1.

Based on that SO question, you might be seeing a different error though. But I'd recommend pulling in this change anyway to get hot reloading working.
